name : Agent Creation

on: push

jobs:
  Agent_Creation_Job1:
      name: Agent Creation Job
      runs-on: windows-latest
      steps:
        - run: echo "This is running inside a ${{ runner.os }} server in Github"
        - name: Check out source code
          uses: actions/checkout@v2.4.2
        - run: echo "This repo is ${{ github.repository }}.."
        - name: Run a inline script
          run:  |
            mkdir newfolder
            ls -l
          shell: bash
        - name: Run a script file from repo
          run: sh ./run.sh
          shell: pwsh
 
        
  
 
