name : Agent Creation

on: push

jobs:
  Agent_Creation_Job1:
      name: Agent Creation Job
      run-on: ubuntu-latest:
      
        steps:
        -run: echo "This is running inside a ${{runner.os}} server in Github"
  

